### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by chillaxkrish** [jajukajulz/foodprint#27]
Please help me

![image](https://user-images.githubusercontent.com/61927056/113516749-a4a8e880-9599-11eb-97c7-27e86f67b958.png)

**Comment by jajukajulz** [comment]
Create a SQL database and add a file called `dbconfig.json` with the login details to the root of the project.

The contents of the file should be as follows:
{

        "db_pool": {
         "connectionLimit" : 10,
        "host"  : <NAME_OF_DB_HOST>,
        "user"     : <DB_LOGIN_NAME>,
        "password" : <DB_LOGIN_PASSWORD>,
        "database" : "<DB_NAME>"
    }
}
